name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        for f in mcp_*/pyproject.toml; do
          if uv pip compile --extra test "$f" &>/dev/null; then
            uv pip install -r <(uv pip compile --extra lint --extra test "$f")
          else
            uv pip install -r <(uv pip compile --extra lint "$f")
          fi
        done
    - name: Check Pylint version
      run: uv run pylint --version
    - name: Analysing the code with pylint
      run: |
        for d in mcp_*; do
          PYTHONPATH="$d" uv run pylint $d/*.py
        done
